replicaCount: 1

image:
  repository: ghcr.io/emd1tey/cv
  pullPolicy: IfNotPresent
  tag: "dev"

service:
  type: ClusterIP
  port: 8000

serviceAccount:
  create: false

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: cv-dev.emditey.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret
      hosts:
        - cv-dev.emditey.xyz

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

