name: "Dependabot Auto Merge and Code Quality"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC

jobs:
  dependabot:
    name: "Dependabot Update and Audit"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
        continue-on-error: true

      - name: Run code quality checks
        run: flake8 .

      - name: Run security audit
        run: pip-audit

      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
