name: "Dependabot Auto Merge and Code Quality"

on:
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main1
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC

jobs:
  dependabot:
    name: "Dependabot Update and Audit"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

      - name: Run tests
        run: pytest
        continue-on-error: true

      - name: Run code quality checks
        run: ruff check .

      - name: Run security audit
        run: pip-audit
