name: Deploy CV to Pages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

    - name: Run code quality checks
      run: ruff check .

    - name: Run tests
      run: pytest
      continue-on-error: true

    - name: Run security audit
      run: pip-audit

    - name: Convert CV html to pdf
      run: python -m src.__main__ --create-docs

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./static

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        branch: main
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ github.event.repository.name }}
        directory: ./static
        wranglerVersion: '3'
