name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto merge dev into main"
          title: "Auto merge dev into main"
          body: "This PR is automatically created to merge changes from dev to main."
          base: main

  build:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

      - name: Run code quality checks
        run: ruff check .

      - name: Run tests
        run: pytest

      - name: Approve the pull request if tests pass
        if: success()
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --base main --head dev --json number --jq '.[0].number')
          gh pr review $PR_NUMBER --repo ${{ github.repository }} --approve
